import './global.css';
import TrpcProvider from './provider/provider';
export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TrpcProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </TrpcProvider>
  );
}
